services:
  database:
    image: postgres
    container_name: quickstart-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - quickstart-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  quickstart-db-data:
    driver: local

